language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
before_install: 
  - 'gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)'
  - 'gem update bundler --conservative'
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CI=true
rvm: 2.6.2
cache: bundler
sudo: false
dist: trusty
