language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
before_install:
  - "gem update --system"
  - "gem install bundler"
env:
  - CI=true
rvm: 2.5.1
cache: bundler
sudo: false
dist: trusty
